version: '3'
services:

  front:
    image: frot
    ports: 
      - 5000:5000
    environment:
      - API_URL=http://localhost:8000

  back:
    image: backdock
    ports:
      - 8000:8000
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=postgres
      - DB_PASSWORD=pwd
      - DB_HOST=db

  redis:
    image: redis    

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_USER=postgres

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
